### ISSUE TITLE
trailing space

### ISSUE THREAD

**Issue by luv2dnce33** [Game4Move78/zsh-bitwarden#2]
plugin copies a trailing space character when piping bwpw/bwus | pbcopy or using the bwup to copy directly to the clipboard from the plugin

> bw get password shopstyle | wc -c
     100
> bwpw shopstyle | wc -c
     101
> bwpw shopstyle | sed 's/.$//' | wc -c
     100

> bwup shopstyle
Hit enter to copy username...
Hit enter to copy password...
> pbpaste | wc -c
     101

**Comment by Game4Move78** [comment]
Should be fixed

**Comment by luv2dnce33** [comment]
this does not seem to work unfortunately.
